version: "3.9"
services:
  cdp:
    depends_on:
      db:
        condition: service_healthy
    build: cdp
    hostname: cdp
    environment:
      - DB=postgresql://cdp:strongPW@db:5432/cdp
      - SECRET_KEY=GenerateRandomSecret
      - AdminToken=RandomTokenDataHere
    ports:
      - 8080:8000
  db:
    image: postgres:latest
    hostname: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cdp"]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=cdp
      - POSTGRES_PASSWORD=strongPW
      - POSTGRES_DB=cdp
    volumes:
      - ~/Desktop/docker/Volumes/pgData:/var/lib/postgresql/data
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    depends_on:
      - cdp
    #image: nginx:latest
    build: frontend
    volumes:
     - ./frontend/html:/usr/share/nginx/html
    ports: 
      - "81:80"
      - "443:443"
    